name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - run: dotnet build -c Debug

    - uses: actions/upload-artifact@v2
      with:
        name: QSB
        path: .\QSB\Bin\Debug